sudo: required
dist: trusty
language: python
virtualenv:
  system_site_packages: false
python:
  - '3.6'
install:
  - sudo apt-get update
  - sudo apt-get install libportaudio0 libportaudio2 libportaudiocpp0 portaudio19-dev
  - pip install -r requirements.txt
script: 
  - python main.py

